workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean Flutter build
        script: |
          flutter clean
          flutter pub get
      - name: Clean Pods cache
        script: |
          cd ios
          pod cache clean --all
          pod deintegrate
          pod repo update
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign --verbose
    artifacts:
      - build/ios/ipa/*.ipa