workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Update CocoaPods specs repository
        script: |
          cd ios
          pod repo update
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign --target-platform ios-13.0
    artifacts:
      - build/ios/ipa/*.ipa