platform :ios, '13.0'

target 'Runner' do

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

  pod 'audioplayers_darwin'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'BoringSSL-GRPC'
        target.build_configurations.each do |config|
          config.build_settings['COMPILER_FLAGS'] = '$(inherited) -w'
        end
      end
    end
  end
end